POST http://localhost:4000/create_user
Content-Type: application/json

{
    "password": "1234",
    "schoolNumber": "10214"
}

################################

GET http://localhost:4000/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "schoolNumber": "10214",
    "password": "1234"
}

### GET
GET http://localhost:4000/question/0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    


### POST
POST http://localhost:4000/question/0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    

{
    "answer_idx":0
}


### POST
POST http://localhost:4000/question/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    

{
    "answer_idx":1
}


### POST
POST http://localhost:4000/question/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    

{
    "answer_idx":2
}


### POST
POST http://localhost:4000/question/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    

{
    "answer_idx":2
}


### POST
POST http://localhost:4000/question/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    

{
    "answer_idx":0
}


### POST
POST http://localhost:4000/question/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    

{
    "answer_idx":1
}



### POST

POST http://localhost:4000/matching
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    

{
    "save_csv":"1"
}


### GET

GET http://localhost:4000/matching
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY  

{
    "save_csv":"1"
}


### GET

GET http://localhost:4000/matching
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxOSIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.bl4cQ8fsQ0_XwWpUfgN_y7XDaXP8EhU8voBvPwe4mHc

{
    "save_csv":"1"
}





### GET
GET http://localhost:4000/matching/status
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiMDNhYzY3NDIxNmYzZTE1Yzc2MWVlMWE1ZTI1NWYwNjc5NTM2MjNjOGIzODhiNDQ1OWUxM2Y5NzhkN2M4NDZmNCJ9.--zei_dBiG6ErUnNUWJL5cDYf9x-wdO-_-RPzMECYQY    



### GET
GET https://yoonhero.pythonanywhere.com/matching
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY2hvb2xOdW1iZXIiOiIxMDIxNCIsInBhc3N3b3JkIjoiNzVjZjJkZGEyYzkwOTRiZWQzZTgwYmU4ZGI5OGU2YWQ5MjRjZWE4OTQ1MzFhMjYxNjFmMWU4MTJmNmRkMGE4NyJ9.KGCAOE1t5lqcrc3eOTCeESeyKNTD7R53G74HmhZlgKw   


